import { Link } from '@tanstack/react-router';
import { RetroButton } from '@/components/ui/retro-button';

export function FiredPage() {
  return (
    <div className="min-h-screen bg-slate-900/5 flex items-center justify-center px-4 py-10">
      <div className="max-w-2xl w-full bg-white rounded-xl shadow-2xl border border-slate-200 font-normal">
        <div className="border-b border-slate-200 bg-slate-50 rounded-t-xl p-6 space-y-3 font-mono text-sm text-slate-700">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2">
            <span className="font-semibold text-slate-500">From:</span>
            <span>HR Automated Notice &lt;no-reply@corpchrono.com&gt;</span>
          </div>
          <div className="flex flex-col sm:flex-row sm:items-center gap-2">
            <span className="font-semibold text-slate-500">To:</span>
            <span>You</span>
          </div>
          <div className="flex flex-col sm:flex-row sm:items-center gap-2">
            <span className="font-semibold text-slate-500">Subject:</span>
            <span>Termination of Employment and Access Revocation</span>
          </div>
        </div>
        <div className="p-8 space-y-4 text-slate-700">
          <p>
            Due to repeated non-compliance with required time-writing procedures, your employment
            with ChronoLog has been terminated effective immediately.
          </p>
          <p>
            All system access has been revoked, including but not limited to VPN, email, building
            entry credentials, workstation authentication, and premium espresso privileges.
          </p>
          <p>
            Please retrieve any remaining personal belongings from your workstation tomorrow between
            08:00 and 08:07 under Facilities supervision.
          </p>
          <p>
            We thank you for your service—especially the compliant days—and wish you success in
            future time-logging environments.
          </p>
          <div className="pt-4">
            <Link to="/login" className="inline-block">
              <RetroButton variant="secondary">Return to login</RetroButton>
            </Link>
          </div>
          <p className="text-xs text-slate-400 text-center">
            This is an automated message generated by the Time Compliance Engine. Please do not
            reply.
          </p>
        </div>
      </div>
    </div>
  );
}
