/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeRouteImport } from './routes/time'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FiredRouteImport } from './routes/fired'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginVoiceRecognitionRouteImport } from './routes/login/voice-recognition'
import { Route as LoginResetPasswordRouteImport } from './routes/login/reset-password'
import { Route as LoginPasswordRouteImport } from './routes/login/password'
import { Route as LoginNetworkErrorRouteImport } from './routes/login/network-error'
import { Route as LoginLoginAgainRouteImport } from './routes/login/login-again'
import { Route as LoginDnaSampleRouteImport } from './routes/login/dna-sample'
import { Route as LoginDanceVerificationRouteImport } from './routes/login/dance-verification'
import { Route as LoginButtonSyncRouteImport } from './routes/login/button-sync'
import { Route as LoginBinaryQuestionRouteImport } from './routes/login/binary-question'

const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FiredRoute = FiredRouteImport.update({
  id: '/fired',
  path: '/fired',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginVoiceRecognitionRoute = LoginVoiceRecognitionRouteImport.update({
  id: '/voice-recognition',
  path: '/voice-recognition',
  getParentRoute: () => LoginRoute,
} as any)
const LoginResetPasswordRoute = LoginResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LoginRoute,
} as any)
const LoginPasswordRoute = LoginPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => LoginRoute,
} as any)
const LoginNetworkErrorRoute = LoginNetworkErrorRouteImport.update({
  id: '/network-error',
  path: '/network-error',
  getParentRoute: () => LoginRoute,
} as any)
const LoginLoginAgainRoute = LoginLoginAgainRouteImport.update({
  id: '/login-again',
  path: '/login-again',
  getParentRoute: () => LoginRoute,
} as any)
const LoginDnaSampleRoute = LoginDnaSampleRouteImport.update({
  id: '/dna-sample',
  path: '/dna-sample',
  getParentRoute: () => LoginRoute,
} as any)
const LoginDanceVerificationRoute = LoginDanceVerificationRouteImport.update({
  id: '/dance-verification',
  path: '/dance-verification',
  getParentRoute: () => LoginRoute,
} as any)
const LoginButtonSyncRoute = LoginButtonSyncRouteImport.update({
  id: '/button-sync',
  path: '/button-sync',
  getParentRoute: () => LoginRoute,
} as any)
const LoginBinaryQuestionRoute = LoginBinaryQuestionRouteImport.update({
  id: '/binary-question',
  path: '/binary-question',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/fired': typeof FiredRoute
  '/login': typeof LoginRouteWithChildren
  '/time': typeof TimeRoute
  '/login/binary-question': typeof LoginBinaryQuestionRoute
  '/login/button-sync': typeof LoginButtonSyncRoute
  '/login/dance-verification': typeof LoginDanceVerificationRoute
  '/login/dna-sample': typeof LoginDnaSampleRoute
  '/login/login-again': typeof LoginLoginAgainRoute
  '/login/network-error': typeof LoginNetworkErrorRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/voice-recognition': typeof LoginVoiceRecognitionRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/fired': typeof FiredRoute
  '/time': typeof TimeRoute
  '/login/binary-question': typeof LoginBinaryQuestionRoute
  '/login/button-sync': typeof LoginButtonSyncRoute
  '/login/dance-verification': typeof LoginDanceVerificationRoute
  '/login/dna-sample': typeof LoginDnaSampleRoute
  '/login/login-again': typeof LoginLoginAgainRoute
  '/login/network-error': typeof LoginNetworkErrorRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/voice-recognition': typeof LoginVoiceRecognitionRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button': typeof ButtonRoute
  '/fired': typeof FiredRoute
  '/login': typeof LoginRouteWithChildren
  '/time': typeof TimeRoute
  '/login/binary-question': typeof LoginBinaryQuestionRoute
  '/login/button-sync': typeof LoginButtonSyncRoute
  '/login/dance-verification': typeof LoginDanceVerificationRoute
  '/login/dna-sample': typeof LoginDnaSampleRoute
  '/login/login-again': typeof LoginLoginAgainRoute
  '/login/network-error': typeof LoginNetworkErrorRoute
  '/login/password': typeof LoginPasswordRoute
  '/login/reset-password': typeof LoginResetPasswordRoute
  '/login/voice-recognition': typeof LoginVoiceRecognitionRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/button'
    | '/fired'
    | '/login'
    | '/time'
    | '/login/binary-question'
    | '/login/button-sync'
    | '/login/dance-verification'
    | '/login/dna-sample'
    | '/login/login-again'
    | '/login/network-error'
    | '/login/password'
    | '/login/reset-password'
    | '/login/voice-recognition'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/button'
    | '/fired'
    | '/time'
    | '/login/binary-question'
    | '/login/button-sync'
    | '/login/dance-verification'
    | '/login/dna-sample'
    | '/login/login-again'
    | '/login/network-error'
    | '/login/password'
    | '/login/reset-password'
    | '/login/voice-recognition'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/button'
    | '/fired'
    | '/login'
    | '/time'
    | '/login/binary-question'
    | '/login/button-sync'
    | '/login/dance-verification'
    | '/login/dna-sample'
    | '/login/login-again'
    | '/login/network-error'
    | '/login/password'
    | '/login/reset-password'
    | '/login/voice-recognition'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonRoute: typeof ButtonRoute
  FiredRoute: typeof FiredRoute
  LoginRoute: typeof LoginRouteWithChildren
  TimeRoute: typeof TimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fired': {
      id: '/fired'
      path: '/fired'
      fullPath: '/fired'
      preLoaderRoute: typeof FiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/voice-recognition': {
      id: '/login/voice-recognition'
      path: '/voice-recognition'
      fullPath: '/login/voice-recognition'
      preLoaderRoute: typeof LoginVoiceRecognitionRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/reset-password': {
      id: '/login/reset-password'
      path: '/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/password': {
      id: '/login/password'
      path: '/password'
      fullPath: '/login/password'
      preLoaderRoute: typeof LoginPasswordRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/network-error': {
      id: '/login/network-error'
      path: '/network-error'
      fullPath: '/login/network-error'
      preLoaderRoute: typeof LoginNetworkErrorRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/login-again': {
      id: '/login/login-again'
      path: '/login-again'
      fullPath: '/login/login-again'
      preLoaderRoute: typeof LoginLoginAgainRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/dna-sample': {
      id: '/login/dna-sample'
      path: '/dna-sample'
      fullPath: '/login/dna-sample'
      preLoaderRoute: typeof LoginDnaSampleRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/dance-verification': {
      id: '/login/dance-verification'
      path: '/dance-verification'
      fullPath: '/login/dance-verification'
      preLoaderRoute: typeof LoginDanceVerificationRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/button-sync': {
      id: '/login/button-sync'
      path: '/button-sync'
      fullPath: '/login/button-sync'
      preLoaderRoute: typeof LoginButtonSyncRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/binary-question': {
      id: '/login/binary-question'
      path: '/binary-question'
      fullPath: '/login/binary-question'
      preLoaderRoute: typeof LoginBinaryQuestionRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginBinaryQuestionRoute: typeof LoginBinaryQuestionRoute
  LoginButtonSyncRoute: typeof LoginButtonSyncRoute
  LoginDanceVerificationRoute: typeof LoginDanceVerificationRoute
  LoginDnaSampleRoute: typeof LoginDnaSampleRoute
  LoginLoginAgainRoute: typeof LoginLoginAgainRoute
  LoginNetworkErrorRoute: typeof LoginNetworkErrorRoute
  LoginPasswordRoute: typeof LoginPasswordRoute
  LoginResetPasswordRoute: typeof LoginResetPasswordRoute
  LoginVoiceRecognitionRoute: typeof LoginVoiceRecognitionRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginBinaryQuestionRoute: LoginBinaryQuestionRoute,
  LoginButtonSyncRoute: LoginButtonSyncRoute,
  LoginDanceVerificationRoute: LoginDanceVerificationRoute,
  LoginDnaSampleRoute: LoginDnaSampleRoute,
  LoginLoginAgainRoute: LoginLoginAgainRoute,
  LoginNetworkErrorRoute: LoginNetworkErrorRoute,
  LoginPasswordRoute: LoginPasswordRoute,
  LoginResetPasswordRoute: LoginResetPasswordRoute,
  LoginVoiceRecognitionRoute: LoginVoiceRecognitionRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonRoute: ButtonRoute,
  FiredRoute: FiredRoute,
  LoginRoute: LoginRouteWithChildren,
  TimeRoute: TimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
